version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: grab
    binary: grab
    main: ./cmd/grab
    goos: [darwin, linux, windows]
    goarch: [amd64, arm64]
    env:
      - CGO_ENABLED=1
      - CC=cc
      - CXX=c++
    ldflags:
      - -s -w
      - -X github.com/epilande/codegrab/internal/utils.Version={{.Version}}
      - -X github.com/epilande/codegrab/internal/utils.CommitSHA={{.ShortCommit}}
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target x86_64-linux-gnu
          - CXX=zig c++ -target x86_64-linux-gnu
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target aarch64-linux-gnu
          - CXX=zig c++ -target aarch64-linux-gnu
      - goos: windows
        goarch: amd64
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target x86_64-windows-gnu
          - CXX=zig c++ -target x86_64-windows-gnu
      - goos: windows
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=zig cc -target aarch64-windows-gnu
          - CXX=zig c++ -target aarch64-windows-gnu
archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
checksum:
  name_template: "checksums.txt"
brews:
  - name: "{{ .ProjectName }}"
    homepage: "https://github.com/epilande/codegrab"
    description: "An interactive CLI tool for selecting and bundling code into a single, LLM-ready output file"
    license: "MIT"
    repository:
      owner: epilande
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    test: |
      system "#{bin}/grab --version"
    install: |
      bin.install "grab"
